// Copyright (c) 2026 Kazarin Dmitry Dmitrievich. Licensed under the MIT License.

#include "ChooserSkill.h"

UChooserAuthoringSkill::UChooserAuthoringSkill()
{
	Description = TEXT(
		"How to author Unreal Chooser Tables: the table signature and its parameters, rows and their "
		"results, filter, scoring and output columns, cell values, and nested tables. Apply this skill "
		"whenever creating or editing a chooser asset, or wiring one into an animation graph or blueprint.");

	Instructions = TEXT(
		"WHAT A CHOOSER TABLE IS\n"
		"- A decision table. Rows hold results; columns hold conditions. Evaluation walks the rows top to\n"
		"  bottom and returns the first row that passes every filter column. If no row passes, the\n"
		"  fallback row is used, and if there is no fallback the table returns null.\n"
		"- Column kinds: filter columns reject rows, scoring columns rank the survivors by cost (lowest\n"
		"  wins), output columns write a value back once a row is chosen, and the Randomize column picks\n"
		"  among the survivors by weight and must be the last column.\n"
		"\n"
		"AUTHORING ORDER\n"
		"1. ChooserTableToolset.CreateChooserTable with the class the rows return (UAnimSequence,\n"
		"   UStaticMesh, a data asset, ...). Use CreateAnimationChooserTable instead when the table feeds\n"
		"   the Chooser Player anim node; it sets up the anim instance and settings parameters for you.\n"
		"2. AddChooserObjectParameter / AddChooserStructParameter for everything the table reads or\n"
		"   writes. Columns can only bind to properties of these, so parameters come first. Mark a\n"
		"   parameter Write or ReadWrite if an output column will write to it.\n"
		"3. ChooserColumnToolset.AddChooserColumn per condition. Pass ParameterIndex and PropertyPath to\n"
		"   bind it in the same call.\n"
		"4. ChooserRowToolset.AddChooserRow per result, then ChooserCellToolset to fill the cells.\n"
		"5. ChooserTableToolset.ValidateChooserTable, then AssetTools.save_assets to write the asset.\n"
		"\n"
		"BINDINGS\n"
		"- Never guess a property path. ListBindableProperties returns every path a column can bind to,\n"
		"  with the ValueKind that says which column types accept it, and it follows nested structs and\n"
		"  object references.\n"
		"- A path is dot separated from the parameter, e.g. \"CharacterMovement.MaxWalkSpeed\". An empty\n"
		"  path binds the parameter itself, which is what an Object column comparing whole objects wants.\n"
		"- Match ValueKind to the column: Float for Float Range and Float Difference, Enum for Enum and\n"
		"  Enum (Or), GameplayTags for Gameplay Tag, and so on. ListChooserColumnTypes reports each\n"
		"  column's ValueKind.\n"
		"\n"
		"CELLS\n"
		"- SetChooserCell takes the value as text in the format ListChooserColumnTypes shows as\n"
		"  CellFormat: \"MatchTrue\" for Bool, \"(Min=100.000000,Max=400.000000,bNoMin=False,bNoMax=False)\"\n"
		"  for Float Range, \"(Comparison=MatchEqual,Value=\\\"Idle\\\")\" for Name, a plain number for\n"
		"  Randomize weights and Output Float.\n"
		"- Use the typed tools where text is awkward: SetChooserEnumCell takes enum value names,\n"
		"  SetChooserGameplayTagCell takes tag names, SetChooserObjectCell and SetChooserClassCell take\n"
		"  real references.\n"
		"- A new row starts from each column's template cell, which AddChooserColumn leaves matching\n"
		"  anything, so only fill the cells that actually constrain the row. DescribeChooserTable reports\n"
		"  that template as DefaultCell and SetChooserColumnDefaultCell changes it. Read it before\n"
		"  assuming an untouched cell is inert: a table authored elsewhere can have a template that\n"
		"  filters, and an enum cell reading \"Comparison=MatchEqual,Value=0\" rejects every row whose\n"
		"  input is not the enum's first value.\n"
		"- Row index -2 is the fallback row. It has cells only in output columns, since it passes no\n"
		"  filters.\n"
		"\n"
		"WRITING WHOLE STRUCTS\n"
		"- An Output Struct column writes a whole struct parameter, so bind it with an empty PropertyPath:\n"
		"  that binds the parameter itself, which is what gives the column its struct type. A column with\n"
		"  no struct type has empty cells and loses them again on every compile.\n"
		"- Its cells carry the type ahead of the values:\n"
		"  \"/Script/MyModule.MyStruct(Field=1,Other=\\\"x\\\")\". Copy the shape out of DefaultCell.\n"
		"- A table whose result type is NoPrimaryResult has rows that exist only to drive output columns.\n"
		"  Add them with AddChooserRow and no result at all, rather than parking a stand-in asset there.\n"
		"- Rows without a result do not end the evaluation. What ends it is a row handing the caller an\n"
		"  object it accepts; with nothing to hand over, every row that passes the filters runs its output\n"
		"  columns in turn and the last one to match is the one whose values remain. \"The first matching\n"
		"  row wins\" holds for the returned object, not for outputs written on the way there.\n"
		"- So either order an outputs-only table general-to-specific, or give its rows results and let the\n"
		"  first match end the evaluation - the reverse of how a result table is usually ordered.\n"
		"\n"
		"WHAT THE CALLER SEES\n"
		"- A Blueprint Evaluate Chooser node has two settings that change what the outputs mean. Mode is\n"
		"  FirstResult or AllResults. StructOutputMode is Default or SingleOutputStruct, and a freshly\n"
		"  placed node comes up as SingleOutputStruct only for backwards compatibility - new content\n"
		"  should use Default.\n"
		"- Only Default combined with AllResults turns a struct output into an array, one entry per\n"
		"  matching row. Every other combination gives a single struct, written once per row the\n"
		"  evaluation reaches.\n"
		"- How many rows it reaches is decided by the results, not by these settings: it walks the rows\n"
		"  that passed the filters, writes their outputs, and stops at the first row whose result yields\n"
		"  an object the caller accepts - non-null, and of the declared result type when the table has\n"
		"  one. A row with no result, or holding an object of another type, is stepped over, and the row\n"
		"  after it overwrites what it just wrote.\n"
		"- With FirstResult, StructOutputMode changes how outputs are read, never which row is chosen. A\n"
		"  table picking the wrong row is a filter, ordering or result problem, not a mode one.\n"
		"- EvaluateChooserTable behaves like SingleOutputStruct: with bReturnAllMatches its Outputs are\n"
		"  what the last matching row wrote.\n"
		"\n"
		"NESTING\n"
		"- A row can hand the decision to another table. Pass a chooser asset to AddChooserRow for an\n"
		"  Evaluate Chooser row, or CreateNestedChooser first and pass that for a Nested Chooser row.\n"
		"- A nested table shares the parameters of the table that owns it and has its own rows and\n"
		"  columns. Add parameters through either table; they always land on the root.\n"
		"\n"
		"AFTER EVERY CHANGE\n"
		"- ValidateChooserTable compiles the table and reports bindings that stopped resolving, rows with\n"
		"  no result, and results that do not match the result class. A column whose binding fails to\n"
		"  compile rejects nothing and silently lets every row through.\n"
		"- EvaluateChooserTable runs the table for real and reports the row it picked, which is the only\n"
		"  way to be sure the cells say what you meant.\n"
		"- Nothing is on disk until AssetTools.save_assets.");
}

UChooserDebuggingSkill::UChooserDebuggingSkill()
{
	Description = TEXT(
		"How to diagnose a chooser table that returns the wrong row, returns nothing, or ignores a "
		"column. Apply this skill when a chooser is already authored but behaves wrongly.");

	Instructions = TEXT(
		"CHECK IN THIS ORDER\n"
		"1. ValidateChooserTable. A binding that no longer resolves is the usual cause: the column stops\n"
		"   filtering, so rows that should be rejected survive and the first row always wins.\n"
		"2. EvaluateChooserTable with the parameters the game passes. Its SelectedRows says which row\n"
		"   won; -2 means every row failed and the fallback was used. Its Outputs shows what the output\n"
		"   columns wrote.\n"
		"3. DescribeChooserTable and read the cells of the row you expected. A cell left at its default\n"
		"   usually matches everything, so a row that should be specific may be passing on a column you\n"
		"   thought constrained it.\n"
		"4. Row order. Two rows can both pass; the earlier one wins. MoveChooserRow reorders them.\n"
		"5. Disabled data. A disabled row or column is kept in the asset but skipped, and\n"
		"   DescribeChooserTable reports both.\n"
		"\n"
		"SYMPTOMS\n"
		"- Always returns the first row: a filter column is unbound, disabled, or every cell is set to\n"
		"  match anything.\n"
		"- A row nobody meant to be picky quietly filters: its cell came from the column's template cell,\n"
		"  which DescribeChooserTable reports as DefaultCell.\n"
		"- An Output Struct column writes nothing and its cells read as empty: it has no struct type,\n"
		"  because its binding points at a property instead of the whole parameter. Rebind it with an\n"
		"  empty PropertyPath.\n"
		"- Always returns null: no row passes and there is no fallback row. Add one with\n"
		"  SetChooserRowResult on row -2, or loosen the filters.\n"
		"- Returns a row whose cells clearly do not match: the column is bound to a different property\n"
		"  than you think. Check ParameterIndex and PropertyPath in DescribeChooserTable, and confirm the\n"
		"  parameter order matches the order the caller passes objects in.\n"
		"- Output values never arrive: the parameter the output column writes to is marked Read. Set it\n"
		"  to Write or ReadWrite with SetChooserParameterDirection.\n"
		"- A Randomize column never varies: it must be the last column, and rows need non-zero weights.\n"
		"- Works in the editor but not in game: pass a RandomSeed to EvaluateChooserTable to remove\n"
		"  randomness from the comparison, and check the game passes parameters in the same order the\n"
		"  table declares them.\n"
		"\n"
		"- Outputs hold values from a row that did not win: the evaluation ran past that row because no\n"
		"  earlier row returned a result the caller could use, so a later match overwrote the outputs.\n"
		"  Give the rows results of the declared type, or reorder them; the caller's mode is not the fix.\n"
		"\n"
		"AGAINST A RUNNING GAME\n"
		"- With Play In Editor running, ListChooserDebugTargets names the objects that recently evaluated\n"
		"  the table. SetChooserDebugTarget follows one, and GetChooserDebugSelectedRows then reports the\n"
		"  rows that object selects as it plays.\n"
		"- Set that target before reading the rows. A table being evaluated by anything else keeps\n"
		"  overwriting the same record, so unclaimed rows describe whichever object ran last, and a lone\n"
		"  -2 means that evaluation fell through to the fallback row, not that nothing ran.\n"
		"- Read the count carefully: a single index is the row the evaluation stopped on, the one that\n"
		"  won. Several indices are every row that passed the filters, recorded when the evaluation ran\n"
		"  to the end without any row returning a usable result. Several indices mean the filters are\n"
		"  loose or the results are missing, not that several rows each won something.");
}
